name: Test
on: workflow_dispatch
concurrency:
  group: test
  cancel-in-progress: true
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        image:
          - alpine
          - android-armv7
          - android-arm64
          - centos7-devtoolset7
          - linux-armv6
          - linux-armv7
          - linux-armv7l-musl
          - linux-arm64
          - linux-arm64-lts
          - linux-arm64-musl
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        uses: docker/build-push-action@v4
        with:
          context: ${{ matrix.image }}
          tags: |
            prebuild/${{ matrix.image }}:dev
          push: false
      - name: Print versions
        run: |
          docker run --rm prebuild/${{ matrix.image }}:dev node -v
          docker run --rm prebuild/${{ matrix.image }}:dev npm -v
          docker run --rm prebuild/${{ matrix.image }}:dev npx -v
          docker run --rm prebuild/${{ matrix.image }}:dev python --version
          docker run --rm prebuild/${{ matrix.image }}:dev npm ls node-gyp -g
      - name: Print env
        run: docker run --rm prebuild/${{ matrix.image }}:dev env

      # TODO: fix WORKDIR and permissions (#10)
      # - name: Test node-gyp
      #   run: docker run --rm -v $(pwd)/test/native-addon:/home/node/app:z -w /home/node/app prebuild/${{ matrix.image }}:dev npm run install
